name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ORG_SSH_KEY }}
      - uses: dart-lang/setup-dart@v1.2
      - uses: actions/checkout@v2

      - name: Check format
        run: flutter format -n --set-exit-if-changed .

      - name: Lint using flutter analyze
        run: flutter analyze
